version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      gha:
        patterns: ["*"]
    open-pull-requests-limit: 3

  - package-ecosystem: pip
    directory: /validator
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      everything:
        patterns: ["*"]
    open-pull-requests-limit: 3
